config/routes.rb
Rails.application.routes.draw do
  resources :quotes

  scope 'api' do
    scope 'v1' do
      scope 'sms' do
        post '/' => 'quotes#sms'
      end
    end
  end

  match 'submit_quote/:id', :to => 'quotes#submit_quote', as: 'quote_submission', via: [:get, :post]

end

app/models/quote.rb
class Quote < ActiveRecord::Base
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/quotes_controller.rb
class QuotesController < ApplicationController
  before_action :set_quote, only: [:show, :edit, :update, :destroy, :submit_quote]
  after_action :submit_quote, only: [:sms]
  skip_before_filter :verify_authenticity_token, :only => [:sms]
  # GET /quotes
  # GET /quotes.json
  def index
    @quotes = Quote.all
  end

  # GET /quotes/1
  # GET /quotes/1.json
  def show
  end

  # GET /quotes/new
  def new
    @quote = Quote.new
  end

  # GET /quotes/1/edit
  def edit
  end

  # POST /quotes
  # POST /quotes.json
  def create
    @quote = Quote.new(quote_params)

    respond_to do |format|
      if @quote.save
        format.html { redirect_to @quote, notice: 'Quote was successfully created.' }
        format.json { render :show, status: :created, location: @quote }
      else
        format.html { render :new }
        format.json { render json: @quote.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /quotes/1
  # PATCH/PUT /quotes/1.json
  def update
    respond_to do |format|
      if @quote.update(quote_params)
        format.html { redirect_to @quote, notice: 'Quote was successfully updated.' }
        format.json { render :show, status: :ok, location: @quote }
      else
        format.html { render :edit }
        format.json { render json: @quote.errors, status: :unprocessable_entity }
      end
    end
  end

  def sms
    @quote = Quote.new
    text_body = request['Body']

    link = text_body.split('/').last
    thumbtack_link = "http://thmtk.com/#{link}"

    @quote.name = thumbtack_link
    @quote.save

    q = @quote

    obtain_thumbtack_quote_info(q)

  end

  def obtain_thumbtack_quote_info(quote)
  
    m = Mechanize.new

    m.get("https://www.thumbtack.com/login") do |login_page|
      loggedin_page = login_page.form_with(:id => 'login') do |form|
        username_field = form.field_with(:id => 'login_email')
        username_field.value = ENV['thumbtack_un']
        password_field = form.field_with(:id => 'login_password')
        password_field.value = ENV['thumbtack_pw']
      end.submit

      lead_page = m.get(quote.name)
      parsed_page = lead_page.parser            
      
            
      quote.type_of_home = parsed_page.css('.request-info')[1].text
      quote.recurrence = parsed_page.css('.request-info')[2].text
      quote.day_preference = parsed_page.css('.request-info')[3].text
      quote.time_preference = parsed_page.css('.request-info')[4].text
      quote.bedrooms = parsed_page.css('.request-info')[5].text
      quote.bathrooms = parsed_page.css('.request-info')[6].text
      quote.square_feet = parsed_page.css('.request-info')[7].text
      quote.cleaning_supplies = parsed_page.css('.request-info')[8].text
      # quote.eco_friendly = parsed_page.css('.request-info')[2].text
      # quote.pets = parsed_page.css('.request-info')[2].text d
      # quote.qndry = parsed_page.css('.request-info')[2].text
      # quote.refrigerator = parsed_page.css('.request-info')[2].text
      # quote.oven = parsed_page.css('.request-info')[2].text
      # quote.windows = parsed_page.css('.request-info')[2].text


      quote.save
    end
  
  end

  def submit_quote

    if @quote.bedrooms == "Studio"
      amount = 119
    elsif @quote.bedrooms == "1 bedroom"
      amount = 129
    elsif @quote.bedrooms == "2 bedrooms"
      amount = 139
    elsif @quote.bedrooms == "3 bedrooms"
      amount = 159
    elsif @quote.bedrooms == "4 bedrooms"
      amount = 189
    elsif @quote.bedrooms == "5 bedrooms"
      amount = 219
    elsif @quote.bedrooms == "5+ bedrooms"
      amount = 249  
    end

    if @quote.recurrence == "Every week"
      discount = 20
    elsif @quote.recurrence == "Every other week"
      discount = 15
    elsif @quote.recurrence == "Once a month"
      discount = 10
    else
      discount = 100
    end

    quoted_value = amount.to_f - amount.to_f * (discount.to_f / 100 )

    m = Mechanize.new

    m.get("https://www.thumbtack.com/login") do |login_page|
      loggedin_page = login_page.form_with(:id => 'login') do |form|
        username_field = form.field_with(:id => 'login_email')
        username_field.value = ENV['thumbtack_un']
        password_field = form.field_with(:id => 'login_password')
        password_field.value = ENV['thumbtack_pw']
      end.submit

      lead_page = m.get(@quote.name).form_with(id: "quote-on-request") do |form|
        form.field_with(:id => 'estimate_type').options[0].click
        quote_price_field = form.field_with(:id => 'estimate_fixed_price_per_unit')
        quote_price_field.value = quoted_value
        quote_message_field = form.field_with(id: 'message')
        quote_message_field.value = "Hi ,\n\nWe have a flat rate for #{@quote.bedrooms}, home of $#{quoted_value}.\n\nAnything else such as laundry, refrigerator, oven, and window cleaning is an extra $25.\n\nBook a cleaning by using our website at www.maidfox.com or call us at (480) 360-6243 (MAID) today.\n\nWe're a top rated Phoenix area service and look forward to working with you!\n\nThanks!\n\nCarlos"
      end.submit      

    end

  end


  # DELETE /quotes/1
  # DELETE /quotes/1.json
  def destroy
    @quote.destroy
    respond_to do |format|
      format.html { redirect_to quotes_url, notice: 'Quote was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_quote
      @quote = Quote.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def quote_params
      params.require(:quote).permit(:name, :quote_type, :type_of_home, :recurrence, :day_preference, :time_preference, :bedrooms, :bathrooms, :square_feet, :cleaning_supplies, :eco_friendly, :qndry, :pets, :refrigerator, :oven, :windows, :location, :request_time)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/quotes_helper.rb
module QuotesHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>TwilioThumb</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/quotes/_form.html.erb
<%= form_for(@quote) do |f| %>
  <% if @quote.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@quote.errors.count, "error") %> prohibited this quote from being saved:</h2>

      <ul>
      <% @quote.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :quote_type %><br>
    <%= f.text_field :quote_type %>
  </div>
  <div class="field">
    <%= f.label :type_of_home %><br>
    <%= f.text_field :type_of_home %>
  </div>
  <div class="field">
    <%= f.label :recurrence %><br>
    <%= f.text_field :recurrence %>
  </div>
  <div class="field">
    <%= f.label :day_preference %><br>
    <%= f.text_field :day_preference %>
  </div>
  <div class="field">
    <%= f.label :time_preference %><br>
    <%= f.text_field :time_preference %>
  </div>
  <div class="field">
    <%= f.label :bedrooms %><br>
    <%= f.text_field :bedrooms %>
  </div>
  <div class="field">
    <%= f.label :bathrooms %><br>
    <%= f.text_field :bathrooms %>
  </div>
  <div class="field">
    <%= f.label :square_feet %><br>
    <%= f.text_field :square_feet %>
  </div>
  <div class="field">
    <%= f.label :cleaning_supplies %><br>
    <%= f.text_field :cleaning_supplies %>
  </div>
  <div class="field">
    <%= f.label :eco_friendly %><br>
    <%= f.check_box :eco_friendly %>
  </div>
  <div class="field">
    <%= f.label :laundry %><br>
    <%= f.check_box :laundry %>
  </div>
  <div class="field">
    <%= f.label :pets %><br>
    <%= f.check_box :pets %>
  </div>
  <div class="field">
    <%= f.label :refrigerator %><br>
    <%= f.check_box :refrigerator %>
  </div>
  <div class="field">
    <%= f.label :oven %><br>
    <%= f.check_box :oven %>
  </div>
  <div class="field">
    <%= f.label :windows %><br>
    <%= f.check_box :windows %>
  </div>
  <div class="field">
    <%= f.label :location %><br>
    <%= f.text_field :location %>
  </div>
  <div class="field">
    <%= f.label :request_time %><br>
    <%= f.text_field :request_time %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/quotes/edit.html.erb
<h1>Editing Quote</h1>

<%= render 'form' %>

<%= link_to 'Show', @quote %> |
<%= link_to 'Back', quotes_path %>

app/views/quotes/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Quotes</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Quote type</th>
      <th>Type of home</th>
      <th>Recurrence</th>
      <th>Day preference</th>
      <th>Time preference</th>
      <th>Bedrooms</th>
      <th>Bathrooms</th>
      <th>Square feet</th>
      <th>Cleaning supplies</th>
      <th>Eco friendly</th>
      <th>Laundry</th>
      <th>Pets</th>
      <th>Refrigerator</th>
      <th>Oven</th>
      <th>Windows</th>
      <th>Location</th>
      <th>Request time</th>
      <th colspan="4"></th>
    </tr>
  </thead>

  <tbody>
    <% @quotes.each do |quote| %>
      <tr>
        <td><%= quote.name %></td>
        <td><%= quote.quote_type %></td>
        <td><%= quote.type_of_home %></td>
        <td><%= quote.recurrence %></td>
        <td><%= quote.day_preference %></td>
        <td><%= quote.time_preference %></td>
        <td><%= quote.bedrooms %></td>
        <td><%= quote.bathrooms %></td>
        <td><%= quote.square_feet %></td>
        <td><%= quote.cleaning_supplies %></td>
        <td><%= quote.eco_friendly %></td>
        <td><%= quote.laundry %></td>
        <td><%= quote.pets %></td>
        <td><%= quote.refrigerator %></td>
        <td><%= quote.oven %></td>
        <td><%= quote.windows %></td>
        <td><%= quote.location %></td>
        <td><%= quote.request_time %></td>
        <td><%= link_to 'Show', quote %></td>
        <td><%= link_to 'Edit', edit_quote_path(quote) %></td>
        <td><%= link_to 'Submit Quote', quote_submission_path(quote) %></td>
        <td><%= link_to 'Destroy', quote, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Quote', new_quote_path %>

app/views/quotes/new.html.erb
<h1>New Quote</h1>

<%= render 'form' %>

<%= link_to 'Back', quotes_path %>

app/views/quotes/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @quote.name %>
</p>

<p>
  <strong>Quote type:</strong>
  <%= @quote.quote_type %>
</p>

<p>
  <strong>Type of home:</strong>
  <%= @quote.type_of_home %>
</p>

<p>
  <strong>Recurrence:</strong>
  <%= @quote.recurrence %>
</p>

<p>
  <strong>Day preference:</strong>
  <%= @quote.day_preference %>
</p>

<p>
  <strong>Time preference:</strong>
  <%= @quote.time_preference %>
</p>

<p>
  <strong>Bedrooms:</strong>
  <%= @quote.bedrooms %>
</p>

<p>
  <strong>Bathrooms:</strong>
  <%= @quote.bathrooms %>
</p>

<p>
  <strong>Square feet:</strong>
  <%= @quote.square_feet %>
</p>

<p>
  <strong>Cleaning supplies:</strong>
  <%= @quote.cleaning_supplies %>
</p>

<p>
  <strong>Eco friendly:</strong>
  <%= @quote.eco_friendly %>
</p>

<p>
  <strong>Laundry:</strong>
  <%= @quote.laundry %>
</p>

<p>
  <strong>Pets:</strong>
  <%= @quote.pets %>
</p>

<p>
  <strong>Refrigerator:</strong>
  <%= @quote.refrigerator %>
</p>

<p>
  <strong>Oven:</strong>
  <%= @quote.oven %>
</p>

<p>
  <strong>Windows:</strong>
  <%= @quote.windows %>
</p>

<p>
  <strong>Location:</strong>
  <%= @quote.location %>
</p>

<p>
  <strong>Request time:</strong>
  <%= @quote.request_time %>
</p>

<%= link_to 'Edit', edit_quote_path(@quote) %> |
<%= link_to 'Back', quotes_path %>